version: "3.3"
services:

  frontend:
    image: ghcr.io/fosten/plone-mountain-site-frontend:${STACK_PARAM:-latest}
    networks:
      - traefik-public
      - traefik-mountain
    environment:
      RAZZLE_INTERNAL_API_PATH: http://lillymountain-com_backend:8080/Plone
      RAZZLE_FARMOS_API_HOST: ${RAZZLE_FARMOS_API_HOST}
      RAZZLE_FARMOS_API_CLIENT_ID: ${RAZZLE_FARMOS_API_CLIENT_ID}
      RAZZLE_FARMOS_API_CLIENT_SECRET: ${RAZZLE_FARMOS_API_CLIENT_SECRET}
      RAZZLE_FARMOS_API_SCOPE: ${RAZZLE_FARMOS_API_SCOPE}
      RAZZLE_FARMOS_API_USERNAME: ${RAZZLE_FARMOS_API_USERNAME}
      RAZZLE_FARMOS_API_PASSWORD: ${RAZZLE_FARMOS_API_PASSWORD}
    ports:
      - "3003:3000"
    depends_on:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.mountain-frontend.loadbalancer.server.port=3000
        # HOSTS: Main
        - traefik.http.routers.mountain-frontend.rule=Host(`lillymountain.com`)
        - traefik.http.routers.mountain-frontend.entrypoints=websecure
        - traefik.http.routers.mountain-frontend.tls=true
        - traefik.http.routers.mountain-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.mountain-frontend.service=mountain-frontend
        - traefik.http.routers.mountain-frontend.middlewares=gzip

  backend:
    image: ghcr.io/fosten/plone-mountain-site-backend:${STACK_PARAM:-latest}
    networks:
      - traefik-public
      - traefik-mountain
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}'"
    ports:
      - "8083:8080"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # SERVICE
        - traefik.http.services.mountain-backend.loadbalancer.server.port=8080
        # MIDDLEWARES
        ### basic_auth Authentication ClassicUI & Zope
        - traefik.http.middlewares.mountain-backend-auth.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6
        - traefik.http.middlewares.mountain-zope-auth.basicauth.users=admin:$$2y$$05$$hGP72w.Rgky4RK7FrN9km.UpdwwHqB8gJNp8TQ4s4qDK8LxjfISl6
        ### Backend ++api++ VHM
        - "traefik.http.middlewares.mountain-vhm-cleanup.replacepathregex.regex=^/((\\+\\+api\\+\\+/){1,})($$|.*)"
        - "traefik.http.middlewares.mountain-vhm-cleanup.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/Plone/++api++/VirtualHostRoot/$$3"
        - "traefik.http.middlewares.mountain-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.mountain-vhm.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/Plone/++api++/VirtualHostRoot/$$1"
        ### Backend ClassicUI VHM
        - "traefik.http.middlewares.mountain-vhm-classicui.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.mountain-vhm-classicui.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/Plone/VirtualHostRoot/_vh_ClassicUI/$$1"
        ### Backend zopeadmin root path
        - "traefik.http.middlewares.mountain-root-zopeadmin.replacepathregex.regex=^/zopeadmin($$|/.*)"
        - "traefik.http.middlewares.mountain-root-zopeadmin.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/VirtualHostRoot/_vh_ClassicUI/manage_main/$$1"

        # ROUTES
        ## lillymountain.com API
        - traefik.http.routers.mountain-backend.rule=Host(`lillymountain.com`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.mountain-backend.entrypoints=websecure
        - traefik.http.routers.mountain-backend.tls=true
        - traefik.http.routers.mountain-backend.service=mountain-backend
        - traefik.http.routers.mountain-backend.middlewares=gzip,mountain-vhm-cleanup,mountain-vhm
        ### lillymountain.com /ClassicUI - protected with basic auth (prevent SEOs from crawl it)
        - traefik.http.routers.mountain-classicui.rule=Host(`lillymountain.com`) && (PathPrefix(`/ClassicUI`))
        - traefik.http.routers.mountain-classicui.entrypoints=websecure
        - traefik.http.routers.mountain-classicui.tls=true
        - traefik.http.routers.mountain-classicui.service=mountain-backend
        - traefik.http.routers.mountain-classicui.middlewares=gzip,mountain-backend-auth,mountain-vhm-classicui
        ### lillymountain.com /zope - protected with basic auth (prevent unauthorized acess)
        - traefik.http.routers.mountain-zopeadmin.rule=Host(`lillymountain.com`) && (PathPrefix(`/zopeadmin`))
        - traefik.http.routers.mountain-zopeadmin.entrypoints=websecure
        - traefik.http.routers.mountain-zopeadmin.tls=true
        - traefik.http.routers.mountain-zopeadmin.service=mountain-backend
        - traefik.http.routers.mountain-zopeadmin.middlewares=gzip,mountain-zope-auth,mountain-root-zopeadmin

networks:
  traefik-public:
    external: true
  traefik-mountain:
    driver: overlay