---
version: '3.9'

services:
  frontend:
    image: ghcr.io/fosten/plone-mountain-site-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://lillymountain-com_backend:8080/Plone
      RAZZLE_API_PATH: https://lillymountain.com
      RAZZLE_FARMOS_API_HOST: ${RAZZLE_FARMOS_API_HOST}
      RAZZLE_FARMOS_API_CLIENT_ID: ${RAZZLE_FARMOS_API_CLIENT_ID}
      RAZZLE_FARMOS_API_CLIENT_SECRET: ${RAZZLE_FARMOS_API_CLIENT_SECRET}
      RAZZLE_FARMOS_API_SCOPE: ${RAZZLE_FARMOS_API_SCOPE}
      FARMOS_API_USERNAME: ${FARMOS_API_USERNAME}
      FARMOS_API_PASSWORD: ${FARMOS_API_PASSWORD}
    depends_on:
      - backend
    networks:
      - traefik-public
      - traefik-mountain
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Service
        - traefik.http.services.mountain-frontend.loadbalancer.server.port=3000
        # Routers
        ## /
        - traefik.http.routers.mountain-frontend.rule=Host(`lillymountain.com`)
        - traefik.http.routers.mountain-frontend.entrypoints=https
        - traefik.http.routers.mountain-frontend.tls=true
        - traefik.http.routers.mountain-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.mountain-frontend.service=mountain-frontend
        - traefik.http.routers.mountain-frontend.middlewares=gzip

  backend:
    image: ghcr.io/fosten/plone-mountain-site-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${DB_NAME:-plone}' user='${DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}' port='${DB_PORT:-5432}'"
    networks:
      - traefik-public
      - traefik-mountain
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Services
        - traefik.http.services.mountain-backend.loadbalancer.server.port=8080
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.mountain-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.mountain-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.mountain-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.mountain-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/lillymountain.com/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.mountain-backend-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

        # Routes
        ## /++api++
        - traefik.http.routers.mountain-backend-api.rule=Host(`lillymountain.com`) && PathPrefix(`/++api++`)
        - traefik.http.routers.mountain-backend-api.entrypoints=https
        - traefik.http.routers.mountain-backend-api.tls=true
        - traefik.http.routers.mountain-backend-api.service=mountain-backend
        - traefik.http.routers.mountain-backend-api.middlewares=gzip,mountain-backend-vhm-api
        ## /ClassicUI
        - traefik.http.routers.mountain-backend-classic.rule=Host(`lillymountain.com`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.mountain-backend-classic.entrypoints=https
        - traefik.http.routers.mountain-backend-classic.tls=true
        - traefik.http.routers.mountain-backend-classic.service=mountain-backend
        - traefik.http.routers.mountain-backend-classic.middlewares=gzip,mountain-backend-auth,mountain-backend-vhm-classic

networks:
  traefik-public:
    external: true
  traefik-mountain:
    internal: true
    driver: overlay
