---
version: '3.9'

services:
  frontend:
    image: ghcr.io/fosten/plone-mountain-site-frontend:${STACK_PARAM:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://testing-lillymountain-com_backend:8080/Plone
      RAZZLE_API_PATH: https://testing.lillymountain.com
      FARMOS_API_HOST: ${FARMTEST_API_HOST}
      FARMOS_API_CLIENT_ID: ${FARMOS_API_CLIENT_ID}
      FARMOS_API_USERNAME: ${FARMOS_API_USERNAME}
      FARMOS_API_PASSWORD: ${FARMOS_API_PASSWORD}
    depends_on:
      - backend
    networks:
      - traefik-public
      - traefik-testing_mountain
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Service
        - traefik.http.services.testing_mountain-frontend.loadbalancer.server.port=3000
        # Middlewares
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_mountain-frontend-auth.basicauth.users=testing:${TRAEFIK_HASHED_PASSWORD}

        # Routers
        ## /
        - traefik.http.routers.testing_mountain-frontend.rule=Host(`testing.lillymountain.com`)
        - traefik.http.routers.testing_mountain-frontend.entrypoints=https
        - traefik.http.routers.testing_mountain-frontend.tls=true
        - traefik.http.routers.testing_mountain-frontend.tls.certresolver=mydnschallenge
        - traefik.http.routers.testing_mountain-frontend.service=testing_mountain-frontend
        - traefik.http.routers.testing_mountain-frontend.middlewares=testing_mountain-frontend-auth

  backend:
    image: ghcr.io/fosten/plone-mountain-site-backend:${STACK_PARAM:-latest}
    environment:
      RELSTORAGE_DSN: "dbname='${TESTING_DB_NAME:-plone}' user='${TESTING_DB_USER:-plone}' host='${DB_HOST:-db}' password='${DB_PASSWORD:-plone}' port='${DB_PORT:-5432}'"
    networks:
      - traefik-public
      - traefik-testing_mountain
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == mountainapp
      labels:
        - traefik.enable=true
        - traefik.swarm.network=traefik-public
        - traefik.constraint-label=traefik-public
        # Services
        - traefik.http.services.testing_mountain-backend.loadbalancer.server.port=8080
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.testing_mountain-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.testing_mountain-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/testing.lillymountain.com/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.testing_mountain-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.testing_mountain-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/testing.lillymountain.com/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - traefik.http.middlewares.testing_mountain-backend-auth.basicauth.users=admin:${TRAEFIK_HASHED_PASSWORD}

        # Routes
        ## /++api++
        - traefik.http.routers.testing_mountain-backend-api.rule=Host(`testing.lillymountain.com`) && PathPrefix(`/++api++`)
        - traefik.http.routers.testing_mountain-backend-api.entrypoints=https
        - traefik.http.routers.testing_mountain-backend-api.tls=true
        - traefik.http.routers.testing_mountain-backend-api.service=testing_mountain-backend
        - traefik.http.routers.testing_mountain-backend-api.middlewares=testing_mountain-backend-vhm-api
        ## /ClassicUI
        - traefik.http.routers.testing_mountain-backend-classic.rule=Host(`testing.lillymountain.com`) && PathPrefix(`/ClassicUI`)
        - traefik.http.routers.testing_mountain-backend-classic.entrypoints=https
        - traefik.http.routers.testing_mountain-backend-classic.tls=true
        - traefik.http.routers.testing_mountain-backend-classic.service=testing_mountain-backend
        - traefik.http.routers.testing_mountain-backend-classic.middlewares=testing_mountain-backend-auth,testing_mountain-backend-vhm-classic

networks:
  traefik-public:
    external: true
  traefik-testing_mountain:
    internal: true
    driver: overlay
